export const GAME_WIDTH = 390;
export const GAME_HEIGHT = 720;

export const settings = {
  gravity: 1180,
  flapVelocity: -390,
  startingObstacleSpeed: 170,
  maxObstacleSpeed: 285,
  speedIncreasePerScore: 5,
  obstacleSpawnMs: 1450,
  obstacleWidth: 72,
  obstacleGap: 184,
  groundHeight: 76,
  playerX: 112,
  audioVolume: 0.42,
  parallax: {
    farClouds: 0.12,
    midClouds: 0.28,
    flamingos: 0.44
  },
  pipeLabels: [
    "Uje",
    "Drita",
    "Rruge",
    "Toka",
    "Deti",
    "Taksat",
    "Buxheti",
    "Borxhi",
    "Koncesione",
    "Tendera",
    "PPP",
    "Inceneratore",
    "Mbetje",
    "Eco Park",
    "Porti Durres",
    "Porto Romano",
    "Sazan",
    "Zvernec",
    "Investime",
    "Strategjike",
    "Privatizim",
    "Energjia",
    "Nafta",
    "Gazsjelles",
    "OSHEE",
    "KESH",
    "Rruge Miliona",
    "Autostrada",
    "Tuneli",
    "Aeroport",
    "Kukes",
    "Vlore",
    "Sarande",
    "Shkoder",
    "Elbasan",
    "Fier",
    "Durres",
    "Tirane",
    "Mjekesi",
    "Spitale",
    "Barnatore",
    "Sigurime",
    "Shendeti",
    "Arsim",
    "Universitet",
    "Shkolla",
    "Tekste",
    "Projekte",
    "Fondet",
    "Donacione",
    "BE Fondet",
    "IPA",
    "Rindertim",
    "Termet",
    "Emergjenca",
    "Polici",
    "Drejtesi",
    "Gjykata",
    "Prokurori",
    "SPAK",
    "Hetime",
    "Arrestime",
    "Skandale",
    "Afera",
    "Korrupsion",
    "Pastrim Parash",
    "Krim",
    "Organizata",
    "Droge",
    "Kokaine",
    "Hashash",
    "Kontrabande",
    "Trukime",
    "Votime",
    "Zgjedhje",
    "Manipulim",
    "Media",
    "Propagande",
    "Reklama",
    "Kontrata",
    "Licenca",
    "Leje",
    "Ndertim",
    "Kulla",
    "Hotele",
    "Resorte",
    "Turizem",
    "Plazh",
    "Vija Bregdetare",
    "Zonat e Mbrojtura",
    "Kune Vain",
    "Velipoje",
    "Butrint",
    "Zhvillim",
    "Investitor",
    "Oligarke",
    "Biznes",
    "Banke",
    "Kredi",
    "Inflacion",
    "Rroga",
    "Pension",
    "Varferi",
    "Papunesi"
  ],
  storageKey: "flappy-rama-best-score",
  aboutBody: [
    "FLAPPY RAMA is a chaotic arcade satire where reality",
    "feels slightly broken and the sky never stays still.",
    "",
    "You play as Rama, flying through waves of absurd",
    "obstacles while the world below turns into noise,",
    "protests, headlines, and endless contradictions.",
    "",
    "Every run is a fight for survival, every point a small",
    "victory against chaos. How long can you stay in the air",
    "before everything catches up to you?"
  ],
  aboutCta: "Join the revolution.\nStand with the flamingos.",
} as const;
